import os
from config.settings.utils import *

S1_SUPERTREND_LENGTH = 7
S1_SUPERTREND_MULTIPLIER = 2.5
S1_LOOKBACK_CANDLES = 80
S1_RSI_PERIOD = 14
S1_VOLUME_MA_PERIOD = 20
S1_RSI_BULL_CONTINUATION = 58
S1_RSI_BEAR_CONTINUATION = 42
S1_RSI_BULL_ENTRY = 55
S1_RSI_BULL_OVERBOUGHT = 75
S1_RSI_BEAR_ENTRY = 45
S1_RSI_BEAR_OVERSOLD = 25
S1_VOLUME_RATIO_MIN = 0.95
S1_CONF_BASE = 0.45
S1_CONF_RSI_BONUS_CAP = 0.14
S1_CONF_VOL_BONUS_CAP = 0.04
S1_MAX_RISK_PCT = 0.05
S1_RR_RATIO = 1.5
S1_TSL_FACTOR = 0.5
S1_MIN_DF_LEN = int(os.getenv("S1_MIN_DF_LEN", "30"))
S1_CONF_BASE_NEW = float(os.getenv("S1_CONF_BASE_NEW", "0.70"))
S1_VOL_RATIO_THRESH = float(os.getenv("S1_VOL_RATIO_THRESH", "1.5"))
S1_CONF_BONUS = float(os.getenv("S1_CONF_BONUS", "0.05"))
S1_CONF_MAX_NEW = float(os.getenv("S1_CONF_MAX_NEW", "0.9"))

S1_REQUIRES_LIVE_BROKER = _flag("S1_REQUIRES_LIVE_BROKER", "false")
S1_REQUIRES_ORB = _flag("S1_REQUIRES_ORB", "false")
