import os
from config.settings.utils import *

S11_SWEEP_LOOKBACK = int(os.getenv("S11_SWEEP_LOOKBACK", "30"))
S11_SWEEP_SWING_BARS = int(os.getenv("S11_SWEEP_SWING_BARS", "2"))
S11_SWEEP_MIN_WICK_BODY = float(os.getenv("S11_SWEEP_MIN_WICK_BODY", "1.15"))
S11_SWEEP_VOL_MULT = float(os.getenv("S11_SWEEP_VOL_MULT", "1.25"))
S11_SWEEP_CLOSE_INSIDE = _flag("S11_SWEEP_CLOSE_INSIDE", "true")
S11_VOL_MA_PERIOD = int(os.getenv("S11_VOL_MA_PERIOD", "20"))
S11_CONF_BASE = float(os.getenv("S11_CONF_BASE", "0.58"))
S11_CONF_VOL_STRONG_THRESHOLD = float(os.getenv("S11_CONF_VOL_STRONG_THRESHOLD", "2.5"))
S11_CONF_VOL_STRONG_BONUS = float(os.getenv("S11_CONF_VOL_STRONG_BONUS", "0.06"))
S11_CONF_VOL_MULT_BONUS = float(os.getenv("S11_CONF_VOL_MULT_BONUS", "0.03"))
S11_CONF_WICK_STRONG_THRESHOLD = float(os.getenv("S11_CONF_WICK_STRONG_THRESHOLD", "3.0"))
S11_CONF_WICK_STRONG_BONUS = float(os.getenv("S11_CONF_WICK_STRONG_BONUS", "0.04"))
S11_CONF_WICK_MIN_BONUS = float(os.getenv("S11_CONF_WICK_MIN_BONUS", "0.02"))
S11_CONF_SWEEP_PCT_STRONG_THRESHOLD = float(os.getenv("S11_CONF_SWEEP_PCT_STRONG_THRESHOLD", "0.15"))
S11_CONF_SWEEP_PCT_STRONG_BONUS = float(os.getenv("S11_CONF_SWEEP_PCT_STRONG_BONUS", "0.03"))
S11_CONF_SWEEP_PCT_MIN_THRESHOLD = float(os.getenv("S11_CONF_SWEEP_PCT_MIN_THRESHOLD", "0.08"))
S11_CONF_SWEEP_PCT_MIN_BONUS = float(os.getenv("S11_CONF_SWEEP_PCT_MIN_BONUS", "0.01"))
S11_CONF_MAX = float(os.getenv("S11_CONF_MAX", "0.84"))
S11_MIN_DF_OFFSET = 2
S11_SCAN_WINDOW_OFFSET = 2
S11_MAX_SWINGS = 8
S11_EPSILON = 0.01

S11_REQUIRES_LIVE_BROKER = _flag("S11_REQUIRES_LIVE_BROKER", "false")
S11_REQUIRES_ORB = _flag("S11_REQUIRES_ORB", "false")
S11_MIN_DF_LEN = int(os.getenv("S11_MIN_DF_LEN", "32"))
