import os
from config.settings.utils import *

S14_ATR_PERIOD = int(os.getenv("S14_ATR_PERIOD", "14"))
S14_ATR_RATIO = float(os.getenv("S14_ATR_RATIO", "0.75"))
S14_BB_PERIOD = int(os.getenv("S14_BB_PERIOD", "20"))
S14_BB_STD = float(os.getenv("S14_BB_STD", "2.0"))
S14_BB_RATIO = float(os.getenv("S14_BB_RATIO", "0.60"))
S14_MIN_COIL_CANDLES = int(os.getenv("S14_MIN_COIL_CANDLES", "4"))
S14_BODY_COMPRESS_PCT = float(os.getenv("S14_BODY_COMPRESS_PCT", "0.30"))
S14_VOL_BREAKOUT_MULT = float(os.getenv("S14_VOL_BREAKOUT_MULT", "1.6"))
S14_EMA_TREND = int(os.getenv("S14_EMA_TREND", "50"))
S14_VOL_MA_PERIOD = int(os.getenv("S14_VOL_MA_PERIOD", "20"))
S14_EMA_MACRO = int(os.getenv("S14_EMA_MACRO", "200"))
S14_ATR_PAST_LOOKBACK = int(os.getenv("S14_ATR_PAST_LOOKBACK", "20"))
S14_BB_PAST_LOOKBACK = int(os.getenv("S14_BB_PAST_LOOKBACK", "20"))
S14_COIL_SCAN_LIMIT = int(os.getenv("S14_COIL_SCAN_LIMIT", "20"))
S14_HV_LOOKBACK = int(os.getenv("S14_HV_LOOKBACK", "60"))
S14_CONF_BASE = float(os.getenv("S14_CONF_BASE", "0.67"))
S14_CONF_COIL_STRONG_THRESHOLD = int(os.getenv("S14_CONF_COIL_STRONG_THRESHOLD", "8"))
S14_CONF_COIL_STRONG_BONUS = float(os.getenv("S14_CONF_COIL_STRONG_BONUS", "0.05"))
S14_CONF_COIL_MIN_BONUS = float(os.getenv("S14_CONF_COIL_MIN_BONUS", "0.03"))
S14_CONF_HV_LOW_THRESHOLD = float(os.getenv("S14_CONF_HV_LOW_THRESHOLD", "0.20"))
S14_CONF_HV_LOW_BONUS = float(os.getenv("S14_CONF_HV_LOW_BONUS", "0.04"))
S14_CONF_HV_MID_THRESHOLD = float(os.getenv("S14_CONF_HV_MID_THRESHOLD", "0.35"))
S14_CONF_HV_MID_BONUS = float(os.getenv("S14_CONF_HV_MID_BONUS", "0.02"))
S14_CONF_BODY_STRONG_THRESHOLD = float(os.getenv("S14_CONF_BODY_STRONG_THRESHOLD", "0.60"))
S14_CONF_BODY_STRONG_BONUS = float(os.getenv("S14_CONF_BODY_STRONG_BONUS", "0.03"))
S14_CONF_BODY_MIN_THRESHOLD = float(os.getenv("S14_CONF_BODY_MIN_THRESHOLD", "0.40"))
S14_CONF_BODY_MIN_BONUS = float(os.getenv("S14_CONF_BODY_MIN_BONUS", "0.01"))
S14_CONF_VOL_STRONG_THRESHOLD = float(os.getenv("S14_CONF_VOL_STRONG_THRESHOLD", "2.0"))
S14_CONF_VOL_STRONG_BONUS = float(os.getenv("S14_CONF_VOL_STRONG_BONUS", "0.03"))
S14_CONF_VOL_MIN_BONUS = float(os.getenv("S14_CONF_VOL_MIN_BONUS", "0.01"))
S14_CONF_EMA200_ALIGN_BONUS = float(os.getenv("S14_CONF_EMA200_ALIGN_BONUS", "0.02"))
S14_CONF_MAX = float(os.getenv("S14_CONF_MAX", "0.86"))
S14_MIN_ATR_BB_COMPRESSION_RATIO = float(os.getenv("S14_MIN_ATR_BB_COMPRESSION_RATIO", "0.80"))
S14_MIN_HV_RANK_CANDLES = int(os.getenv("S14_MIN_HV_RANK_CANDLES", "5"))
S14_DEFAULT_HV_RANK = float(os.getenv("S14_DEFAULT_HV_RANK", "0.5"))
S14_EPSILON = float(os.getenv("S14_EPSILON", "0.01"))

S14_REQUIRES_LIVE_BROKER = _flag("S14_REQUIRES_LIVE_BROKER", "false")
S14_REQUIRES_ORB = _flag("S14_REQUIRES_ORB", "false")
S14_MIN_DF_LEN_RUNNER = int(os.getenv("S14_MIN_DF_LEN_RUNNER", "35"))

RUNNER_EARLY_TRIGGER_MIN_CONF = 0.62
RUNNER_EARLY_TRIGGER_HIGH_CONF = 0.70
RUNNER_EARLY_TRIGGER_STRENGTH_THRESHOLD = 0.70
RUNNER_EARLY_TRIGGER_STRENGTH_HIGH = 0.78
RUNNER_EARLY_TRIGGER_WEIGHTED_SCORE_THRESHOLD = 0.78
RUNNER_EARLY_TRIGGER_WEIGHTED_SCORE_HIGH = 0.90
RUNNER_EARLY_TRIGGER_BONUS_CANDLE = 0.08
RUNNER_REVERSION_STRENGTH_THRESHOLD = 0.68
RUNNER_REVERSION_WEIGHTED_SCORE_THRESHOLD = 0.76

OB_LOOKBACK = 50
OB_IMPULSE_ATR_MULT = 1.5
OB_RETRACE_TOLERANCE = 0.003
OB_VOL_MULT = 1.05
OB_MIN_BODY_PCT = 0.3

SWING_BARS = 3
BOS_LOOKBACK = 40
BOS_CONFIRM_CLOSE = True

BREAKER_MAX_AGE = 30




