import os
from config.settings.utils import *

SMC_MIN_SWINGS = 4
SMC_MIN_STRUCTURE_SWINGS = 2
SMC_MAX_SWINGS_TRACKED = 16
SMC_PREMIUM_DISCOUNT_SWING_WINDOW = 4
SMC_PREMIUM_DISCOUNT_NEUTRAL = 0.5
SMC_ORDER_BLOCK_SCAN_START = 2
SMC_ORDER_BLOCK_SCAN_END_OFFSET = 2
SMC_ORDER_BLOCK_IMPULSE_LOOKAHEAD_END = 0
SMC_MIN_CANDLE_RANGE = 0.01
SMC_MAX_ORDER_BLOCKS = 10
SMC_VOLUME_AVG_WINDOW = 20
SMC_DEFAULT_VOLUME_RATIO = 1.0
SMC_BOS_CONFIDENCE = 0.65
SMC_CHOCH_CONFIDENCE = 0.63
SMC_META_ROUND_DIGITS = 2
SMC_LOCATION_ROUND_DIGITS = 3
SMC_CONFIDENCE_ROUND_DIGITS = 4
SMC_SCORE_OB_BOS_PD = 0.80
SMC_SCORE_OB_BOS = 0.74
SMC_SCORE_OB_PD = 0.70
SMC_SCORE_BREAKER_BOS = 0.74
SMC_SCORE_BREAKER = 0.68
SMC_DEFAULT_SCORE = 0.66
SMC_FRESH_OB_BARS_TIER_1 = 10
SMC_FRESH_OB_BARS_TIER_2 = 20
SMC_FRESH_OB_BONUS_TIER_1 = 0.03
SMC_FRESH_OB_BONUS_TIER_2 = 0.01
SMC_CHOCH_SCORE_BONUS = 0.02
SMC_VOLUME_BONUS_THRESHOLD_HIGH = 1.8
SMC_VOLUME_BONUS_THRESHOLD_LOW = 1.2
SMC_VOLUME_BONUS_HIGH = 0.03
SMC_VOLUME_BONUS_LOW = 0.01
SMC_MAX_CONFIDENCE = 0.87
SMC_ATR_PERIOD = 14
SMC_ATR_FALLBACK = 50.0
