import os
from config.settings.utils import *

S2_EMA_SHORT = 9
S2_EMA_LONG = 21
S2_MACD_FAST = 12
S2_MACD_SLOW = 26
S2_MACD_SIGNAL = 9
S2_RECENT_CROSS_LOOKBACK = 4
S2_CONF_CROSS_BASE = 0.45
S2_CONF_CROSS_GAP_BONUS = 0.13
S2_CONF_CROSS_GAP_DIVISOR = 10.0
S2_CONF_TREND_BASE = 0.58
S2_CONF_TREND_GAP_BONUS = 0.12
S2_CONF_TREND_GAP_DIVISOR = 8.0

S2_REQUIRES_LIVE_BROKER = _flag("S2_REQUIRES_LIVE_BROKER", "false")
S2_REQUIRES_ORB = _flag("S2_REQUIRES_ORB", "false")
S2_MIN_DF_LEN = int(os.getenv("S2_MIN_DF_LEN", "26"))
