import os
from config.settings.utils import *

S3_MAX_HOUR = 12
S3_VOL_MA_PERIOD = 10
S3_VOL_INCREASE_FACTOR = 1.15
S3_BUFFER_RANGE_MULTIPLIER = 0.04
S3_BUFFER_MIN_POINTS = 5.0
S3_RETEST_BUFFER_MULTIPLIER = 0.4
S3_CONF_MAX = 0.84
S3_CONF_BASE = 0.45
S3_CONF_STRENGTH_MULTIPLIER = 0.16

S3_REQUIRES_LIVE_BROKER = _flag("S3_REQUIRES_LIVE_BROKER", "false")
S3_REQUIRES_ORB = _flag("S3_REQUIRES_ORB", "true")
S3_MIN_DF_LEN = int(os.getenv("S3_MIN_DF_LEN", "20"))
