import os
from config.settings.utils import *

S4_BB_LENGTH = 20
S4_BB_STD = 2.0
S4_STOCH_K = 14
S4_STOCH_D = 3
S4_STOCH_SMOOTH = 3
S4_BBW_MA_PERIOD = 30
S4_BBW_SQUEEZE_FACTOR = 0.85
S4_BULL_STOCH_K = 55
S4_BEAR_STOCH_K = 45
S4_CONFIDENCE = 0.60
S4_MIN_DF_LEN = 20

S4_REQUIRES_LIVE_BROKER = _flag("S4_REQUIRES_LIVE_BROKER", "false")
S4_REQUIRES_ORB = _flag("S4_REQUIRES_ORB", "false")
