"""
Auto-extracted Position Manager thresholds.
"""
import os

POS_MANAGER_PROB_THRESH_0_32 = float(os.getenv("POS_MANAGER_PROB_THRESH_0_32", "0.32"))
POS_MANAGER_RANK_THRESH_0_52 = float(os.getenv("POS_MANAGER_RANK_THRESH_0_52", "0.52"))
POS_MANAGER_RANK_THRESH_0_58 = float(os.getenv("POS_MANAGER_RANK_THRESH_0_58", "0.58"))
POS_MANAGER_RANK_THRESH_0_6 = float(os.getenv("POS_MANAGER_RANK_THRESH_0_6", "0.6"))
POS_MANAGER_RANK_THRESH_0_62 = float(os.getenv("POS_MANAGER_RANK_THRESH_0_62", "0.62"))
POS_MANAGER_RANK_THRESH_0_63 = float(os.getenv("POS_MANAGER_RANK_THRESH_0_63", "0.63"))
POS_MANAGER_RANK_THRESH_0_66 = float(os.getenv("POS_MANAGER_RANK_THRESH_0_66", "0.66"))

POS_MANAGER_PNL_PCT_THRESH_minus_5_5 = float(os.getenv("POS_MANAGER_PNL_PCT_THRESH_MINUS_5_5", "-5.5"))
POS_MANAGER_PNL_PCT_THRESH_minus_2_2 = float(os.getenv("POS_MANAGER_PNL_PCT_THRESH_MINUS_2_2", "-7.5"))  # relaxed from -2.2
POS_MANAGER_PNL_PCT_THRESH_minus_1_2 = float(os.getenv("POS_MANAGER_PNL_PCT_THRESH_MINUS_1_2", "-5.0"))  # relaxed from -1.2
POS_MANAGER_PNL_PCT_THRESH_minus_1_1 = float(os.getenv("POS_MANAGER_PNL_PCT_THRESH_MINUS_1_1", "-5.0"))  # relaxed from -1.1

POS_MANAGER_PNL_PCT_THRESH_0_0 = float(os.getenv("POS_MANAGER_PNL_PCT_THRESH_0_0", "0.0"))
POS_MANAGER_PNL_PCT_THRESH_0_5 = float(os.getenv("POS_MANAGER_PNL_PCT_THRESH_0_5", "0.5"))
POS_MANAGER_PNL_PCT_THRESH_1_0 = float(os.getenv("POS_MANAGER_PNL_PCT_THRESH_1_0", "1.0"))
POS_MANAGER_PNL_PCT_THRESH_35_0 = float(os.getenv("POS_MANAGER_PNL_PCT_THRESH_35_0", "35.0"))
POS_MANAGER_PNL_PCT_THRESH_55_0 = float(os.getenv("POS_MANAGER_PNL_PCT_THRESH_55_0", "55.0"))

POS_MANAGER_LAST_MOMENTUM_THRESH_0_45 = float(os.getenv("POS_MANAGER_LAST_MOMENTUM_THRESH_0_45", "0.45"))
POS_MANAGER_LAST_MOMENTUM_THRESH_0_5 = float(os.getenv("POS_MANAGER_LAST_MOMENTUM_THRESH_0_5", "0.5"))
POS_MANAGER_LAST_MOMENTUM_THRESH_0_68 = float(os.getenv("POS_MANAGER_LAST_MOMENTUM_THRESH_0_68", "0.68"))
POS_MANAGER_MOMENTUM_THRESH_0_55 = float(os.getenv("POS_MANAGER_MOMENTUM_THRESH_0_55", "0.55"))
