from .modules.strategies.base import *
from .modules.strategies.s1 import *
from .modules.strategies.s2 import *
from .modules.strategies.s3 import *
from .modules.strategies.s4 import *
from .modules.strategies.s5 import *
from .modules.strategies.s6 import *
from .modules.strategies.s7 import *
from .modules.strategies.s8 import *
from .modules.strategies.s9 import *
from .modules.strategies.s10 import *
from .modules.strategies.s11 import *
from .modules.strategies.s12 import *
from .modules.strategies.s13 import *
from .modules.strategies.s14 import *
from .modules.strategies.s15 import *
from .modules.strategies.s16 import *
from .modules.strategies.s17 import *
from .modules.strategies.s18 import *
from .modules.strategies.s19 import *
from .modules.strategies.s20 import *
from .modules.strategies.s21 import *
from .modules.strategies.s22 import *
from .modules.strategies.s23 import *
from .modules.strategies.s24 import *
from .modules.strategies.s25 import *
from .modules.strategies.s26 import *
from .modules.strategies.s27 import *
from .modules.strategies.s28 import *
from .modules.strategies.s29 import *
from .modules.strategies.s30 import *
from .modules.strategies.s31 import *
from .modules.strategies.s32 import *
