import os
from config.settings.utils import *

DYN_EXIT_ATR_SL_MULTIPLIER = 2.0
DYN_EXIT_ATR_SL_MIN_PCT = 4.0
DYN_EXIT_ATR_SL_MAX_PCT = 10.0
DYN_EXIT_ATR_PERIOD = 14
DYN_EXIT_SL_TRENDING_STRONG = 8.0
DYN_EXIT_TARGET_TRENDING_STRONG = 42.0
DYN_EXIT_SL_TRENDING_WEAK = 10.0
DYN_EXIT_TARGET_TRENDING_WEAK = 36.0
DYN_EXIT_SL_RANGING = 30.0
DYN_EXIT_TARGET_RANGING = 32.0
DYN_EXIT_SL_CHOPPY = 20.0
DYN_EXIT_TARGET_CHOPPY = 30.0
DYN_EXIT_STOP_LOSS_PCT = 10.0
DYN_EXIT_TARGET_PCT = 150.0
DYN_EXIT_EM_FRACTION = 0.5
DYN_EXIT_EM_MIN_OTM_PCT = 0.3
DYN_EXIT_EM_MAX_OTM_PCT = 3.0
DYN_EXIT_NIFTY_STRIKE_STEP = 50
from config.settings.modules.trading import NIFTY_LOT_SIZE, NIFTY_STRIKE_STEP

SPOT_SL_RISK_PER_TRADE_PCT = 1.0
SPOT_SL_STOP_LOSS_PCT = 25.0
SPOT_SL_NIFTY_LOT_SIZE = NIFTY_LOT_SIZE
SPOT_SL_NIFTY_STRIKE_STEP = NIFTY_STRIKE_STEP
SPOT_SL_RISK_PER_TRADE_PCT = 1.0
SPOT_SL_SWING_LOOKBACK = 20
SPOT_SL_SWING_BARS_EACH_SIDE = 3
SPOT_SL_ATR_SL_MULTIPLIER = 1.5
SPOT_SL_MIN_SL_DISTANCE_PCT = 0.3
SPOT_SL_MAX_SL_DISTANCE_PCT = 2.5
SPOT_SL_OI_ROUND_STEP = 100
SPOT_SL_VWAP_BUFFER_PCT = 0.1
HOT_RELOAD_WATCH_INTERVAL_S = 30
SMART_ENTRY_RISK_PER_TRADE_PCT = 1.0
SMART_ENTRY_DAILY_CAPITAL_PCT = 15.0
SMART_ENTRY_NIFTY_LOT_SIZE = NIFTY_LOT_SIZE
SMART_ENTRY_STOP_LOSS_PCT = 25.0
SMART_ENTRY_RISK_PER_TRADE_PCT = 1.0
SMART_ENTRY_DELTA_SELLER_ZONE_LOW = 0.40
SMART_ENTRY_DELTA_SELLER_ZONE_HIGH = 0.55
SMART_ENTRY_DELTA_MIN_BUY = 0.40
SMART_ENTRY_GAMMA_MIN_BUY = 0.0007
SMART_ENTRY_GAMMA_SELLER_ACTIVE = 0.0007
SMART_ENTRY_MOMENTUM_ADX_MIN = 25.0
SMART_ENTRY_MOMENTUM_RSI_BULL = 60.0
SMART_ENTRY_MOMENTUM_RSI_BEAR = 40.0
SMART_ENTRY_MOMENTUM_ATR_BUFFER = 0.5
SMART_ENTRY_REVERSAL_ATR_BUFFER = 0.25
SMART_ENTRY_ACCUMULATION_ATR_BUFFER = 1.5
SMART_ENTRY_SETUP_CONFIDENCE_MIN = 0.55
